export enum Events {
  CREATE_GUILDS = 'CREATE_GUILDS',
  CREATE_ATTACKS = 'CREATE_ATTACKS',
  CREATE_PLAYERS = 'CREATE_PLAYERS',
  CREATE_ARMS = 'CREATE_ARMS',
  CREATE_ITEMS = 'CREATE_ITEMS',
  CREATE_ARTS = 'CREATE_ARTS',
  CREATE_GUILD = 'CREATE_GUILD',
  CREATE_ATTACK = 'CREATE_ATTACK',
  CREATE_PLAYER = 'CREATE_PLAYER',
  CREATE_ARM = 'CREATE_ARM',
  CREATE_ART = 'CREATE_ART',
  CREATE_ITEM = 'CREATE_ITEM',
  EDIT_GUILD = 'EDIT_GUILD',
  EDIT_ATTACK = 'EDIT_ATTACK',
  EDIT_PLAYER = 'EDIT_PLAYER',
  EDIT_ARM = 'EDIT_ARM',
  EDIT_ART = 'EDIT_ART',
  EDIT_ITEM = 'EDIT_ITEM',
  DELETE_GUILD = 'DELETE_GUILD',
  DELETE_ATTACK = 'DELETE_ATTACK',
  DELETE_PLAYER = 'DELETE_PLAYER',
  DELETE_ARM = 'DELETE_ARM',
  DELETE_ART = 'DELETE_ART',
  DELETE_ITEM = 'DELETE_ITEM'
}

export default Events;